package com.floyd.onebuy.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.floyd.onebuy.dao.BuyCarNumber;
import com.floyd.onebuy.dao.Search;
import com.floyd.onebuy.dao.FridayBuyCarNumber;

import com.floyd.onebuy.dao.BuyCarNumberDao;
import com.floyd.onebuy.dao.SearchDao;
import com.floyd.onebuy.dao.FridayBuyCarNumberDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig buyCarNumberDaoConfig;
    private final DaoConfig searchDaoConfig;
    private final DaoConfig fridayBuyCarNumberDaoConfig;

    private final BuyCarNumberDao buyCarNumberDao;
    private final SearchDao searchDao;
    private final FridayBuyCarNumberDao fridayBuyCarNumberDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        buyCarNumberDaoConfig = daoConfigMap.get(BuyCarNumberDao.class).clone();
        buyCarNumberDaoConfig.initIdentityScope(type);

        searchDaoConfig = daoConfigMap.get(SearchDao.class).clone();
        searchDaoConfig.initIdentityScope(type);

        fridayBuyCarNumberDaoConfig = daoConfigMap.get(FridayBuyCarNumberDao.class).clone();
        fridayBuyCarNumberDaoConfig.initIdentityScope(type);

        buyCarNumberDao = new BuyCarNumberDao(buyCarNumberDaoConfig, this);
        searchDao = new SearchDao(searchDaoConfig, this);
        fridayBuyCarNumberDao = new FridayBuyCarNumberDao(fridayBuyCarNumberDaoConfig, this);

        registerDao(BuyCarNumber.class, buyCarNumberDao);
        registerDao(Search.class, searchDao);
        registerDao(FridayBuyCarNumber.class, fridayBuyCarNumberDao);
    }
    
    public void clear() {
        buyCarNumberDaoConfig.getIdentityScope().clear();
        searchDaoConfig.getIdentityScope().clear();
        fridayBuyCarNumberDaoConfig.getIdentityScope().clear();
    }

    public BuyCarNumberDao getBuyCarNumberDao() {
        return buyCarNumberDao;
    }

    public SearchDao getSearchDao() {
        return searchDao;
    }

    public FridayBuyCarNumberDao getFridayBuyCarNumberDao() {
        return fridayBuyCarNumberDao;
    }

}
