package com.floyd.onebuy.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FRIDAY_BUY_CAR_NUMBER".
 */
public class FridayBuyCarNumber {

    private Long id;
    private Long userId;
    private Long productLssueId;
    private Integer buyNumber;

    public FridayBuyCarNumber() {
    }

    public FridayBuyCarNumber(Long id) {
        this.id = id;
    }

    public FridayBuyCarNumber(Long id, Long userId, Long productLssueId, Integer buyNumber) {
        this.id = id;
        this.userId = userId;
        this.productLssueId = productLssueId;
        this.buyNumber = buyNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getProductLssueId() {
        return productLssueId;
    }

    public void setProductLssueId(Long productLssueId) {
        this.productLssueId = productLssueId;
    }

    public Integer getBuyNumber() {
        return buyNumber;
    }

    public void setBuyNumber(Integer buyNumber) {
        this.buyNumber = buyNumber;
    }

}
