package com.yyg365.interestbar.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.yyg365.interestbar.dao.FridayBuyCarNumber;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FRIDAY_BUY_CAR_NUMBER".
*/
public class FridayBuyCarNumberDao extends AbstractDao<FridayBuyCarNumber, Long> {

    public static final String TABLENAME = "FRIDAY_BUY_CAR_NUMBER";

    /**
     * Properties of entity FridayBuyCarNumber.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, Long.class, "userId", false, "USER_ID");
        public final static Property ProductLssueId = new Property(2, Long.class, "productLssueId", false, "PRODUCT_LSSUE_ID");
        public final static Property BuyNumber = new Property(3, Integer.class, "buyNumber", false, "BUY_NUMBER");
    };


    public FridayBuyCarNumberDao(DaoConfig config) {
        super(config);
    }
    
    public FridayBuyCarNumberDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FRIDAY_BUY_CAR_NUMBER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" INTEGER," + // 1: userId
                "\"PRODUCT_LSSUE_ID\" INTEGER," + // 2: productLssueId
                "\"BUY_NUMBER\" INTEGER);"); // 3: buyNumber
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FRIDAY_BUY_CAR_NUMBER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FridayBuyCarNumber entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        Long productLssueId = entity.getProductLssueId();
        if (productLssueId != null) {
            stmt.bindLong(3, productLssueId);
        }
 
        Integer buyNumber = entity.getBuyNumber();
        if (buyNumber != null) {
            stmt.bindLong(4, buyNumber);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FridayBuyCarNumber readEntity(Cursor cursor, int offset) {
        FridayBuyCarNumber entity = new FridayBuyCarNumber( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // productLssueId
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // buyNumber
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FridayBuyCarNumber entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setProductLssueId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setBuyNumber(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FridayBuyCarNumber entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FridayBuyCarNumber entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
